fortran_compiler:  # [unix]
  - gfortran  # [unix]

m2w64_fortran_compiler:  # [win]
  - m2w64-toolchain  # [win] 
c_compiler:    # [win]
  - vs2019       # [win]
cxx_compiler:  # [win]
  - vs2019       # [win]
vc:            # [win]
  - 14           # [win]
