{% set name = "rosco" %}
{% set version = "2.9.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/ROSCO/archive/v{{ version }}.tar.gz
  sha256: 98ba68e9388156c77473292fd058554160aaf4e2eb3a4db1fa47b18c7aff92c2
  patches:
    - setup.patch
    
build:
  number: 0
  skip: true  # [py<39]
  #detect_binary_files_with_prefix: False  # [osx]
  #binary_relocation: False  # [osx]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    #- export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DCMAKE_FIND_FRAMEWORK=NEVER -DCMAKE_FIND_APPBUNDLE=NEVER"  # [ not win ]
    #- set CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=$%LIBRARY_PREFIX% -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DCMAKE_FIND_FRAMEWORK=NEVER -DCMAKE_FIND_APPBUNDLE=NEVER"  # [ win ]


requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('fortran') }}
    # - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}   # [win]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - cmake
    - make  # [ not win ]
    - pip
    - pkg-config
    - python
    - python-build
    - wheel
  host:
    - python
    - setuptools
    - pip
  run:
    - control
    - matplotlib-base
    - pandas
    - pyYAML
    - pyparsing
    - python
    - pyzmq
    - scipy
    - wisdem >=3.5
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\\libdiscon.dll exit 1  # [win]
  imports:
    - rosco
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
    - gbarter
