{% set name = "rosco" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/rosco/archive/v{{ version }}.tar.gz
  sha256: b6a2cda92680cf6a460d194901a2f16c2635710a82788576a6383a3bb189fc83

build:
  number: 0
  skip: true  # [win and linux]
  preserve_egg_dir: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make  # [not win]
    - cmake
  host:
    - libpython  # [win]
    - python
    - numpy
    - setuptools
    - pandas
    - future
    - pyYAML
    - scipy
    - pytest
    - matplotlib
    - wisdem
    - control
    - pyzmq
    - mpi4py
    - treon
  run:
    - python
    - matplotlib
    - numpy
    - pytest
    - pandas
    - future
    - scipy
    - pyYAML
    - wisdem
    - control
    - pyzmq
    - mpi4py
    - treon

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]
  imports:
    - ROSCO_toolbox
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
