{% set name = "rosco" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/ROSCO/archive/refs/tags/v2.8.0.tar.gz
  sha256: 7a2e3a7bebdf6ee73884a9e3502f904cc3a3f1aa1bf672c223ecbaa041bfc48f

build:
  number: 0
  skip: true  # [py<39]



requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    # - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}   # [win]
    # - {{ compiler('vc') }}              # [win]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - make  # [not win]
    - cmake
    - compilers # [osx]
    # - vc =9  # [win]
    # - vc =14   # [win]
  host:
    # - libpython  # [win]
    - python
    - setuptools
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy
    - wisdem >=3.5
    # - control

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]
  imports:
    - ROSCO_toolbox
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
