{% set name = "rosco" %}
{% set version = "2.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/ROSCO/archive/v{{ version }}.tar.gz
  sha256: 4fd32df2fd30b82364b5a4f60718a14938656da4353c4565679752aab6da62d1
  patches:
    - numpy2.patch
build:
  number: 0
  skip: true  # [py<39]
    #detect_binary_files_with_prefix: False  # [osx]
    #binary_relocation: False  # [osx]
  script:
        # Want to use the conda pkg-config, not the mingw one
    - del /s /q {{ BUILD_PREFIX }}\Library\mingw-w64\bin\pkg-config*      # [win]
    - set "CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%"      # [ win ]
    - {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - cmake                                      # [build_platform != target_platform]
    - cmake-build-extension                      # [build_platform != target_platform]
    - pkg-config                                 # [build_platform != target_platform]
    - make                                       # [ not win ]
    - {{ stdlib('c') }}                          # [ not win ]
    - {{ compiler('c') }}                        # [ not win ]
    - {{ compiler('fortran') }}                  # [ not win ]
    - {{ compiler('m2w64_fortran') }}            # [ win ]
    - {{ compiler('m2w64_c') }}                  # [ win ]
        # The m2w64 linker and pkg-config is too fragile and frustrating to get it to work with zmq
        # Maybe when flang gets more stable this will work on windows.  For now, the windows build just won't have it
  host:
    - python
    - setuptools
    - cmake-build-extension
    - pip
    - zeromq
  run:
    - control
    - matplotlib-base
    - pandas
    - pyYAML
    - pyparsing
    - python
    - pyzmq
    - scipy
    - wisdem >=3.5
    - numpy

test:
  imports:
    - rosco
  source_files:
    - Examples
    - Examples/example_inputs
    - Examples/Test_Cases
    - Examples/Test_Cases/NREL-5MW
    - Examples/Tune_Cases
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT      # [not win]
    - if not exist %LIBRARY_LIB%\\libdiscon.dll exit 1      # [win]
    - cd Examples
    - python 01_turbine_model.py
    - python 04_simple_sim.py
    - cd ..

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
    - gbarter
