{% set name = "rosco" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/ROSCO/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c6e2ffec5321d4752c67a4ab91ea2b5de85c88e9f04d5b936bbb6971f3ccb15
  patches:
    - setup.patch
build:
  number: 3
  skip: true  # [py<=39]
    #detect_binary_files_with_prefix: False  # [osx]
    #binary_relocation: False  # [osx]
  script:
      # Want to use the conda pkg-config, not the mingw one
    - del /s /q {{ BUILD_PREFIX }}\Library\mingw-w64\bin\pkg-config*      # [win]
    - set "CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%"      # [ win ]
    - {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - cmake                                      # [build_platform != target_platform]
    - cmake-build-extension                      # [build_platform != target_platform]
    - pkg-config                                 # [build_platform != target_platform]
    - make                                       # [ not win ]
    - {{ stdlib('c') }}                          # [ not win ]
    - {{ compiler('c') }}                        # [ not win ]
    - {{ compiler('fortran') }}                  # [ not win ]
    - {{ compiler('m2w64_fortran') }}            # [ win ]
    - {{ compiler('m2w64_c') }}                  # [ win ]
  host:
    - cmake-build-extension
    # For some reason adding this one adds odd cmake arguments that are unrecognized and errors
    #- libpython                                  # [win]
    - numpy
    - pip
    - python
    - setuptools
    - zeromq
  run:
    # Windows folks have to add control package through pip otherwise fortran library clash
    - control          # [ not win ]
    - matplotlib-base
    - numpy
    - pandas
    - pyYAML
    - pyparsing
    - python
    - pyzmq
    - scipy
    - wisdem >=3.16

test:
  imports:
    - rosco
  requires:
    - pip
    - simpy
  source_files:
    - Examples
    - Examples/example_inputs
    - Examples/Test_Cases
    - Examples/Test_Cases/NREL-5MW
    - Examples/Tune_Cases
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT      # [not win]
    - if not exist %LIBRARY_LIB%\\libdiscon.dll exit 1      # [win]
    - pip install orbit-nrel openfast_io
    - cd Examples
    - python 01_turbine_model.py
    - python 04_simple_sim.py
    - cd ..

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
    - gbarter
