{% set name = "rosco" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/rosco/archive/v{{ version }}.tar.gz
  sha256: e6a36bc52ce7a13a8e53e2258d0823b84cd451e5cfd64eff40bc6ee861a90f82

build:
  number: 0
  skip: True  # [win and linux]

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make  # [not win]
    - cmake
  host:
    - libpython  # [win]
    - python
    - numpy
    - setuptools
    - pandas
    - future
    - pyYAML
    - scipy
    - pytest
    - matplotlib
    - wisdem
  run:
    - python
    - matplotlib
    - numpy 
    - pytest
    - pandas
    - future
    - scipy
    - pyYAML
    - wisdem

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]
  imports:
    - ROSCO_toolbox
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
