{% set name = "rosco" %}
{% set version = "2.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/ROSCO/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dd2122dafefe2b387694c75b025c86c63d0cab54313929747612d46e64991965
  #patches:
  #  - numpy2.patch
build:
  number: 2
  skip: true  # [py<=39]
    #detect_binary_files_with_prefix: False  # [osx]
    #binary_relocation: False  # [osx]
  script:
        # Want to use the conda pkg-config, not the mingw one
    - del /s /q {{ BUILD_PREFIX }}\Library\mingw-w64\bin\pkg-config*      # [win]
    - set "CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%"      # [ win ]
    - {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - cmake                                      # [build_platform != target_platform]
    - cmake-build-extension                      # [build_platform != target_platform]
    - pkg-config                                 # [build_platform != target_platform]
    - make                                       # [ not win ]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
  host:
    - python
    - setuptools
    - cmake-build-extension
    - pip
    - zeromq
  run:
    - control
    - matplotlib-base
    - pandas
    - pyYAML
    - pyparsing
    - python
    - pyzmq
    - scipy
    - wisdem >=3.16
    - numpy

test:
  imports:
    - rosco
  requires:
    - pip
    - simpy
  source_files:
    - Examples
    - Examples/example_inputs
    - Examples/Test_Cases
    - Examples/Test_Cases/NREL-5MW
    - Examples/Tune_Cases
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT      # [not win]
    - if not exist %LIBRARY_LIB%\\libdiscon.dll exit 1      # [win]
    - pip install marmot-agents openfast_io
    - cd Examples
    - python 01_turbine_model.py
    - python 04_simple_sim.py
    - cd ..

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
    - gbarter
