{% set name = "rosco" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rafmudaf/ROSCO/archive/refs/heads/main.zip
  sha256: d7b6b4ab7eaeb1d94aea5ed2bd9beddfaaaf76f2630c94fb238c613d8d35b409

build:
  number: 0
  # skip: true  # [win and vc>9]


requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}   # [win]
    - {{ compiler('vc') }}              # [win]
    - make  # [not win]
    - cmake
  host:
    # - libpython  # [win]
    - python
    - setuptools
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy
    - wisdem
    - control
    - vc =14   # [win]
    - vc =9  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]
  imports:
    - ROSCO_toolbox
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
