{% set name = "rosco" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/rosco/archive/v{{ version }}.tar.gz
  sha256: 55fe7bba612321baa6e089ee1156ef4db2e3bccf1b69534829b06f3367fff05d

build:
  number: 0
  skip: true  # [win and linux]

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make  # [not win]
    - cmake
  host:
    - libpython  # [win]
    - python
    - numpy
    - setuptools
    - pandas
    - future
    - pyYAML
    - scipy
    - pytest
    - matplotlib
    - wisdem
    - control
  run:
    - python
    - matplotlib
    - numpy
    - pytest
    - pandas
    - future
    - scipy
    - pyYAML
    - wisdem
    - control

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]
  imports:
    - ROSCO_toolbox
about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
    - dzalkind
