{% set name = "rosco" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/rosco/archive/v{{ version }}.tar.gz
  sha256: d872802289755355fb8253823b23da8b718b6b81631a606583e403006a044633

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make  # [not win]
    - cmake
  host:
    - m2w64-toolchain  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
