{% set name = "rosco" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://github.com/nrel/rosco/archive/v{{ version }}.tar.gz
#   sha256: 92bd7169efa9b0c69049875a2e178a8533944cf6c89b567c72ee835581bd2d4e

source:
  git_url: https://github.com/openfast/openfast.git
  git_rev: v{{ version }}
  git_depth: 1

build:
  number: 0
 
requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make  # [not win]
    - cmake
  host:
    - m2w64-toolchain  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libdiscon$SHLIB_EXT  # [not win]
    - if not exist %LIBRARY_LIB%\libdiscon.dll exit 1  # [win]

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas
